import Proofs.Simplify

/-!
# The bridge to the Rust engine

Everything proved in this directory is about the definitions in this directory.
It says nothing about `core/src/calculus.rs` — Lean cannot see that file.

This module closes as much of that gap as is honestly possible without extracting
code. It renders expressions in the engine's own syntax and evaluates the
*verified* derivative with machine floats, so the Rust test suite can differentiate
the same expression with its own rules and check that the two agree. A mismatch
means the shipped rules and the proved rules have drifted apart.
-/

namespace Kosmos

/-- Exact power by repeated multiplication, so the expected values do not depend
on the host's `pow` implementation. -/
def fpow (b : Float) : Nat → Float
  | 0 => 1.0
  | n + 1 => b * fpow b n

/-- Integer to float, built from `Int.natAbs` and `Float.ofNat` so it does not
depend on which conversion helpers a given Lean version happens to ship. -/
def intToFloat (n : Int) : Float :=
  if n < 0 then -(Float.ofNat n.natAbs) else Float.ofNat n.natAbs

/-- A computable float evaluator, used only to produce expected values.

Deliberately *not* the function the theorems talk about — those concern `eval`,
which lives in ℝ and is noncomputable. What is verified here is the structure
being evaluated: the output of `simplify (derive e)`. -/
def evalFloat : Expr → Float → Float
  | .const c, _ => intToFloat c.num / Float.ofNat c.den
  | .var, x => x
  | .add a b, x => evalFloat a x + evalFloat b x
  | .sub a b, x => evalFloat a x - evalFloat b x
  | .mul a b, x => evalFloat a x * evalFloat b x
  | .neg a, x => -evalFloat a x
  | .pow a n, x => fpow (evalFloat a x) n
  | .sin a, x => Float.sin (evalFloat a x)
  | .cos a, x => Float.cos (evalFloat a x)
  | .exp a, x => Float.exp (evalFloat a x)

/-- Print an expression in the syntax the engine's parser accepts. Brackets are
placed conservatively — the goal is a string Rust can parse, not a pretty one. -/
def render : Expr → String
  | .const c =>
      if c.den == 1 then
        if c.num < 0 then "(" ++ toString c.num ++ ")" else toString c.num
      else
        "(" ++ toString c.num ++ "/" ++ toString c.den ++ ")"
  | .var => "x"
  | .add a b => "(" ++ render a ++ " + " ++ render b ++ ")"
  | .sub a b => "(" ++ render a ++ " - " ++ render b ++ ")"
  | .mul a b => "(" ++ render a ++ " * " ++ render b ++ ")"
  | .neg a => "(-" ++ render a ++ ")"
  | .pow a n => "(" ++ render a ++ " ^ " ++ toString n ++ ")"
  | .sin a => "sin(" ++ render a ++ ")"
  | .cos a => "cos(" ++ render a ++ ")"
  | .exp a => "exp(" ++ render a ++ ")"

/-- Expressions to export. Every rule is exercised at least twice, including
nested inside another, so one wrong rule in Rust cannot hide behind a right one. -/
def corpus : List Expr :=
  let x : Expr := .var
  [ .pow x 3,
    .mul (.const 3) (.pow x 2),
    .sub (.pow x 3) (.mul (.const 3) x),
    .sin x,
    .cos x,
    .exp x,
    .sin (.pow x 2),
    .cos (.mul (.const 2) x),
    .exp (.mul (.const 2) x),
    .mul x (.sin x),
    .mul (.sin x) (.cos x),
    .sin (.sin x),
    .exp (.sin (.pow x 2)),
    .add (.mul (.const 4) (.pow x 5)) (.neg (.pow x 2)),
    .pow (.add x (.const 1)) 4,
    .mul (.pow x 2) (.exp (.neg x)),
    .sin (.add (.mul (.const 2) x) (.const 1)),
    .neg (.cos (.pow x 3)),
    .sub (.exp x) (.sin (.exp x)),
    .mul (.mul x x) (.cos (.mul x x)) ]

def samplePoints : List Float := [-2.25, -1.0, -0.4, 0.0, 0.35, 1.0, 2.5]

private def caseLines (e : Expr) : String :=
  let d := simplify (derive e)
  let header := "case " ++ render e ++ " => " ++ render d
  let points := samplePoints.map fun x =>
    "at " ++ toString x ++ " " ++ toString (evalFloat d x)
  String.intercalate "\n" (header :: points)

/-- Emit the corpus in a line format the Rust test suite can read without pulling
in a JSON parser. -/
def exportCases : String :=
  "# generated by proofs/Proofs/Bridge.lean from the verified derive\n"
    ++ "# do not edit by hand: regenerate with tools/verify.ps1\n"
    ++ "# 'case <expression> => <derivative>' followed by 'at <x> <dy>' samples\n"
    ++ String.intercalate "\n\n" (corpus.map caseLines)
    ++ "\n"

end Kosmos

def main : IO Unit := IO.println Kosmos.exportCases
